service: github-actions
plugins:
  - serverless-offline
  - serverless-webpack
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  index:
    handler: src/index.main

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'yarn'
    includeModules: true

